### ISSUE TITLE
Search the base_schedule VJ

### ISSUE THREAD

**Issue by prhod** [CanalTP/kirin#146]
To search the base_schedule in navitia, use : 
- The train number : nouvelleVersion/numeroCourse
- The first departure time +/- 1h of a station : first item in listePointDeParcours having :
  -  "CD", "CH", "FD", "FH", empty or undefined as typeArret
  - a value for "horaireVoyageurDepart"

We use "listeJourRegimeDApplication" do determine the day of first departure time (using the minimal date).
To determine the time of day, we use "horaireVoyageurDepart/heureLocale".

No use of "nbJoursPasseMinuit" is done so far (this might soon be an issue)

**Comment by pbougue** [comment]
It occured to me that itwould be better to actually look for [first -1h; last + 1h] period (like on IRE) because we are not certain that the first stop is the one we have in Navitia (garage for example).
So it seems safer that way, but open to debate.

Once we get VJs from Navitia we could do smarter thing, like matching stop_times to get the best VJ if we have multiple ones... But to me it's another feature.
